server:
  port: 5560

spring:
  application:
    name: LMS-EMICalculator
  datasource:
    username: LMS
    password: sarasu10
    url: jdbc:oracle:thin:@localhost:1522:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone=http: //localhost:8761/eureka
