server:
  port: 5050

spring:
  application:
    name: LMS-API-GetWay

  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: security-service
          uri: lb://LMS-SecurityService
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

        - id: query-service
          uri: lb://LMS-QueryService
          predicates:
            - Path=/query/**
          filters:
            - StripPrefix=1

        - id: action-service
          uri: lb://LMS-ActionService
          predicates:
            - Path=/action/**
          filters:
            - StripPrefix=1

        - id: emi-calc-service
          uri: lb://LMS-EMICalculator
          predicates:
            - Path=/emi/**
          filters:
            - StripPrefix=1

        - id: email-service
          uri: lb://LMS-EmailService
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone=http: //localhost:8761/eureka