server:
  port: 5557

spring:
  application:
    name: LMS-QueryService
  datasource:
    username: LMS
    password: sarasu10
    url: jdbc:oracle:thin:@localhost:1522:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    name: logs/app.log