server:
  port: 5554

spring:
  application:
    name: LMS-SecurityService

  datasource:
    username: LMS
    password: sarasu10
    url: jdbc:oracle:thin:@localhost:1522:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false

eureka:
  client:
    service-url:
      defaultZone=http: //localhost:8761/eureka