server:
  port: 5571

spring:
  application:
    name: LMS-EmailService
  mail:
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: email-sending-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone=http: //localhost:8761/eureka