server:
  port: 5556

spring:
  application:
    name: LMS-ActionService
  datasource:
    username: LMS
    password: sarasu10
    url: jdbc:oracle:thin:@localhost:1522:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true