server:
  port: 5556

spring:
  application:
    name: LMS-ActionService
  datasource:
    username: LMS
    password: sarasu10
    url: jdbc:oracle:thin:@localhost:1522:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone=http: //localhost:8761/eureka
